# Use the official Node.js image as the base image
FROM node:23.11.0 AS build

# Set the working directory inside the container
WORKDIR /app/backend
RUN mkdir /app/shared

# Copy package.json and package-lock.json to the working directory
COPY backend/package.json backend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY backend /app/backend
COPY shared /app/shared

# Build the TypeScript code
RUN npm run build

FROM node:24.0.1-alpine

# Set the working directory inside the container
WORKDIR /app/backend

# Create a directory for sqlite database
RUN mkdir /data
ENV DB_FILE_PATH=/data/eddsi-db.sqlite

# Copy the built application from the build stage
COPY --from=build /app/backend/dist ./dist
COPY --from=build /app/backend/package.json .
COPY --from=build /app/backend/package-lock.json .

# Install only production dependencies
RUN npm install --omit=dev

# Expose the port your application will run on (if applicable)
EXPOSE 3001
ENV HTTP_PORT=3001

# Define the command to run the application
CMD ["node", "dist/backend/src/index.js"]